### PR TITLE
Fix glide not working on individual override channels

### LINKED ISSUE #24: Glide not functional on channel 2, 3 and 4
**Describe the bug**
Glide knobs do nothing when legato notes are sent on their corresponding channels 2, 3, 4

**Steps To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Turn up glide knob
2. Play two notes in legato i.e hold one note then hold another on midi keyboard / sequencer

**Actual behavior**
Second note plays but glide does not function.

**Expected behavior**
Should glide to frequency of next note.

**Additional context**
Being that channel 2 , 3, and 4 are most likely going to be Sequenced the glide function should be compatible with how monophonic sequencers handle slides, (different to how it works on the main channel) , if therapsid receives a note on, on say note 61 then another note on, on 72, that's followed immediately by a note off from 61, it should continue its glide. The way the main channel does it, is nice for playing on a keyboard, but it isn't compatible with slide functions on sequencers.

### PR DESCRIPTION
**Pull request by Windfisch**
Closes #24

### CODE REVIEW

File: src/isr.cpp [hunk 1]
```diff
@@ -174,10 +174,8 @@ void isr() {
 		}
 	}
 	// glides
-	// in monophonic mode, we glide only while the old note is still held down.
-	bool skip_glide = !preset_data.is_polyphonic() && voice_state.n_held_keys() <= 1;
 	for (int i = 0; i < 6; i++) {
-		glide[i].glide_tick(skip_glide ? 0 : preset_data.voice[voice_index[i]].glide);
+		glide[i].glide_tick(voice_state.shall_glide(i) ? preset_data.voice[voice_index[i]].glide : 0);
```
Comment (Windfisch) [inline src/isr.cpp:178]: @twisted-electrons look how while we let the `VoiceState` *decide* whether or not to glide, still the `isr.cpp` file is in control to *actually* instruct our `Glide` objects to glide slowly or infinitely-quickly.

File: src/isr.cpp [hunk 2]
```diff
@@ -174,10 +174,8 @@ void isr() {
 		}
 	}
 	// glides
-	// in monophonic mode, we glide only while the old note is still held down.
-	bool skip_glide = !preset_data.is_polyphonic() && voice_state.n_held_keys() <= 1;
```
Comment (Windfisch) [inline src/isr.cpp:178]: @twisted-electrons this was causing the bug, because `voice_state.n_held_keys()` only counts the keys held on the *master* channel. That means, when playing legato notes on channels 2,3,4, it comes to the conclusion "no legato notes on the main channel -> no glide"

File: src/isr.cpp (hunk 1 above)
Comment (Windfisch) [reply src/isr.cpp:178]: also note that this needs to be tested on real hardware; this timer ISR handler is on a pretty tight time budget and we changed the code to make 6 decisions instead of just one. Hopefully this doesn't overrun our time budget (if so, some more changes are needed.)
